---
name: ark
version: 17.08.1
summary: Work with file archives
description: |-
    Ark is a graphical file compression/decompression utility with support for multiple formats, including tar, gzip, bzip2, rar and zip, as well as CD-ROM images. Ark can be used to browse, extract, create, and modify archives.

    Features:

    - Several formats supported: gzip, bzip2, zip, rar, 7z and more
    - Preview file contents without extracting files
confinement: strict
grade: stable
apps:
    ark:
        command: kf5-launch ark
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.ark
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    kde-frameworks-5-dev:
        plugin: dump
        prime:
        - "-*"
        source: https://build.neon.kde.org/job/kde-frameworks-5-release_amd64.snap/lastSuccessfulBuild/artifact/kde-frameworks-5-dev_amd64.tar.xz
    kde-frameworks-5-env:
        plugin: dump
        prime:
        - kf5-launch
        - kf5
        source: https://github.com/apachelogger/kf5-snap-env.git
    ark:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - kdoctools-dev
        - libarchive-dev
        - libbz2-dev
        - libkf5khtml-dev
        - liblzma-dev
        - libqjson-dev
        - zlib1g-dev
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/ark-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
